"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MachineStatus = void 0;
var MachineStatus;
(function (MachineStatus) {
    MachineStatus["disconnected"] = "disconnected";
    MachineStatus["starting"] = "starting";
    MachineStatus["updating"] = "updating";
    MachineStatus["off"] = "off";
    MachineStatus["Halted"] = "halted";
    MachineStatus["Pausing"] = "pausing";
    MachineStatus["paused"] = "paused";
    MachineStatus["resuming"] = "resuming";
    MachineStatus["cancelling"] = "cancelling";
    MachineStatus["processing"] = "processing";
    MachineStatus["simulating"] = "processing";
    MachineStatus["busy"] = "busy";
    MachineStatus["changingTool"] = "changingTool";
    MachineStatus["idle"] = "idle";
})(MachineStatus = exports.MachineStatus || (exports.MachineStatus = {}));
